Site/Site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'), name='polls'),
    path('blogs/', include('blogs.urls'), name='blogs'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                           document_root=settings.MEDIA_ROOT)

Site/blogs/urls.py
from django.urls import path
from . import views
app_name = 'blogs'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:Blog_id>/', views.detail, name='detail'),
    path('create', views.create, name='create'),
    path('success_saved', views.success_saved, name='success_saved'),
    path('<int:Blog_id>/update', views.Update.as_view(), name='update'),
    path('<int:Blog_id>/delete', views.Delete.as_view(), name='delete'),
]

Site/blogs/models.py
from django.utils import timezone
import datetime
from django.db import models


class Blog(models.Model):
    DoesNotExist = None
    title = models.CharField(max_length=200)
    task = models.TextField()
    pub_date = models.DateTimeField(default=timezone.now(), verbose_name="Time published")
    cover = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'/MyBlogs/{self.id}'

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

Site/blogs/forms.py
from django.forms import ModelForm, TextInput, Textarea, DateTimeField
from .models import Blog


class CreateForm(ModelForm):
   class Meta:
       model = Blog
       fields = ['title', 'task', 'pub_date', 'cover']

       widgets = {
           "title": TextInput(attrs={
               'class': 'form-control',
               'placeholder': 'Название блога'
           }),
           'task': Textarea(attrs={
               'class': 'form-control',
               'placeholder': 'Текст блог'
           }),

    }

Site/blogs/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.template import loader
from django.urls import reverse
from django.views.generic import UpdateView, DeleteView

from .forms import CreateForm
from .models import Blog


def index(request):
    latest_blog_list = Blog.objects.order_by('-pub_date')[:10]
    template = loader.get_template('blogs/Index.html')
    context = {
        'latest_blog_list': latest_blog_list,
    }
    return render(request, 'blogs/index.html', context)

def detail(request, Blog_id):
    try:
        blog = Blog.objects.get(pk=Blog_id)
    except Blog.DoesNotExist:
        raise Http404("Блога не существует")
    return render(request, 'blogs/detail.html', {'blog': blog})


def create(request):
    error =''
    if request.method == 'POST':
        form = CreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blogs:success_saved'))
        else:
            error = 'Wrong form filling'

    form = CreateForm()
    data = {
        'form': form,
        'error': error
    }
    return render(request, 'blogs/create.html', data)


def success_saved(request):
    return render(request, 'blogs/success_saved.html')


class Update(UpdateView):
    model = Blog
    pk_url_kwarg = "Blog_id"
    template_name = 'blogs/update.html'
    form_class = CreateForm
    success_url = '/blogs/'


class Delete(DeleteView):
    model = Blog
    pk_url_kwarg = "Blog_id"
    success_url = '/blogs/'
    template_name = 'blogs/delete.html'

Site/blogs/templates/blogs/create.html
  <style>
   BODY {
    background: linear-gradient(to bottom right, white, red) no-repeat;
   }
   </style>
    <h1>
        <p align="center">
        Создание Блога
    </h1>
    <form method="post" enctype="multipart/form-data">
        <p align="center">
        {% csrf_token %}
        {{ form.title }}<br><br>
        {{ form.task }}<br><br>
        {{ form.cover }}<br><br>
        {{ form.pub_date }}<br><br>
        <span>{{ error }}</span>
        <button class="btn btn-success" type="submit">Добавить блог</button>
    </form>

Site/blogs/templates/blogs/delete.html
  <style>
   BODY {
    background: linear-gradient(to bottom right, white, red) no-repeat;
   }
   </style>
    <h1>
        <p align="center">
        Удаление блога<br>
    </h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p align="center">
        <button  type="submit">Удалить блог</button>
    </form>

Site/blogs/templates/blogs/detail.html
  <style>
   BODY {
    background: linear-gradient(to bottom right, white, red) no-repeat;
   }
   </style>
       <style>
           .blok1, .blok2 {
                border-radius: 4px;
           }
           .blok1 {
              float:left;
              width:700px;
              height:600px;
              text-align: center;
              vertical-align: middle;
          }
          .blok2 {
              vertical-align: middle;
              float:right;
              width:700px;
              height:600px;
              text-align: center;
          }
       </style>
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                  <h1>
                    <p align="center" style="color:#DC143C; font-size:30px">
                    {{ blog.title }}
                </h1>
            <div class="blok1">
                    <div align="left">
                    <figure>
                        <p vertical-align="middle"></p>
                        <img src="{{ blog.cover.url }}">
                    </figure>
                    </div>
            </div>
            <div class="blok2">
                    <div align="left" style="color:black; font-size:20px">
                        {{ blog.task }}
                    </div>
                    <p align="right" style="color:#DC143C; font-size:20px">
            </div><br>
                <h3>
                    <p align="center" style="margin-top: 440px">
                    <button style="width:350px" onclick="document.location='../'">Назад</button>
                    <button style="width:350px" onclick="document.location='update'">Редактировать</button>
                    <button style="width:350px" onclick="document.location='delete'">Удалить</button>
                </h3>

Site/blogs/templates/blogs/index.html
  <style>
   BODY {
    background: linear-gradient(to bottom right, black, red) no-repeat;
   }
   </style>
     <h1>
        <p align="center" style="font-size:35px">
        Список блогов
    </h1>
     <h2>
        {% if latest_blog_list %}
            <ul>
            {% for blog in latest_blog_list %}
               <p align="left" style="color:#DC143C; font-size:35px">
               <p><li><a href="{% url 'blogs:detail' blog.id %}">{{ blog.title }}<br></a></li></p>
            {% endfor %}
            </ul>
        {% else %}
             <p>Блогов нет.</p>
        {% endif %}
     </h2>
    <h4>
<button  style="height:40px;width:120px" onclick="document.location='create'">Создать блог</button>
<button  style="height:40px;width:120px" onclick="document.location='../polls'">Опросы</button>
    </h4>

Site/blogs/templates/blogs/success_saved.html
  <style>
   BODY {
    background: linear-gradient(to bottom right, white, red) no-repeat;
   }
   </style>
    <h1>
        <p align="center">
        Блог сохранен<br>
    </h1>
    <h2>
        <p align="center">
        <button  style="height:50px;width:200px" onclick="document.location='../blogs/'">Назад</button>
    </h2>

Site/blogs/templates/blogs/update.html
  <style>
   BODY {
    background: linear-gradient(to bottom right, white, red) no-repeat;
   }
   </style>
    <h1>
        <p align="center">
        Редактирование Блога
    </h1>
    <form method="post" enctype="multipart/form-data">
        <p align="center">
        {% csrf_token %}
        {{ form.title }}<br><br>
        {{ form.task }}<br><br>
        {{ form.cover }}<br><br>
        {{ form.pub_date }}<br><br>
        <span>{{ error }}</span>
        <button  onclick="document.location='blogs/{{ Blog_id }}'" type="submit">Изменить блог</button>
    </form>